=== parcel-bundler/parcel/packages/utils/parcelforvscode/schemas/parcelrc.schema.json
{
  "title": "JSON schema for .parcelrc files",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "allowTrailingCommas": true,
  "$defs": {
    "plugin": {
      "type": "string"
    },
    "plugins": {
      "defaultSnippets": [
        {
          "body": ["$1", "..."]
        }
      ],
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/plugin"
      }
    },
    "pluginGlobMap": {
      "type": "object",
      "properties": {},
      "additionalProperties": {
        "$ref": "#/$defs/plugin"
      }
    },
    "pluginsGlobMap": {
      "type": "object",
      "properties": {},
      "additionalProperties": {
        "$ref": "#/$defs/plugins"
      }
    }
  },
  "properties": {
    "extends": {
      "oneOf": [
        {
          "$ref": "#/$defs/plugin"
        },
        {
          "$ref": "#/$defs/plugins"
        }
      ],
      "default": "@parcel/extends-default"
    },
    "bundler": {
      "description": "Transform the entire asset graph by grouping the assets into the output bundles.",
      "$ref": "#/$defs/plugin"
    },
    "resolvers": {
      "description": "Resolve a dependency to a file path or virtual module.",
      "$ref": "#/$defs/plugins"
    },
    "transformers": {
      "description": "Compile individual source files and extract dependencies.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "validators": {
      "description": "Validates individual assets and can throw errors or log warnings with diagnostics to validate the input.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "namers": {
      "description": "Determine the name of an output bundle.",
      "$ref": "#/$defs/plugins"
    },
    "packagers": {
      "description": "Combine multiple assets together into a single output bundle.",
      "$ref": "#/$defs/pluginGlobMap"
    },
    "optimizers": {
      "description": "Minify, optimize, and transform output bundles.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "compressors": {
      "description": "Compress and encode output bundles in multiple formats.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "reporters": {
      "description": "Receive events on build progress and completion.",
      "$ref": "#/$defs/plugins"
    },
    "runtimes": {
      "description": "Return additional assets to be inserted into a bundle.",
      "$ref": "#/$defs/plugins"
    }
  },
  "additionalProperties": false,
  "default": {
    "extends": "@parcel/config-default"
  }
}

=== parcel-bundler/parcel/packages/configs/atlassian-ssr/index.json
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
    "bundle-text:*": ["@parcel/transformer-inline-string", "..."],
    "data-url:*": ["@parcel/transformer-inline-string", "..."],
    "*.worker.{js,mjs,jsm,jsx,es6,ts,tsx}": [
      "@parcel/transformer-workerize",
      "..."
    ],
    "*.{js,mjs,jsm,jsx,es6,ts,tsx}": [
      "@parcel/transformer-sync-dynamic-import",
      "@parcel/transformer-babel",
      "@parcel/transformer-js"
    ],
    "*.{json,json5}": ["@parcel/transformer-json"],
    "*.toml": ["@parcel/transformer-toml"],
    "*.yaml": ["@parcel/transformer-yaml"],
    "*.{gql,graphql}": ["@parcel/transformer-graphql"],
    "*.{styl,stylus}": ["@parcel/transformer-stylus"],
    "*.{sass,scss}": ["@parcel/transformer-sass"],
    "*.less": ["@parcel/transformer-less"],
    "*.css": ["@parcel/transformer-postcss", "@parcel/transformer-css"],
    "*.sss": ["@parcel/transformer-sugarss"],
    "*.{htm,html}": [
      "@parcel/transformer-posthtml",
      "@parcel/transformer-html"
    ],
    "*.pug": ["@parcel/transformer-pug"],
    "*.coffee": ["@parcel/transformer-coffeescript"],
    "*.mdx": ["@parcel/transformer-mdx"],
    "*.{eot,gif,jpg,jpeg,ico,mp4,png,svg,ttf,woff}": [
      "@parcel/transformer-raw"
    ],
    "url:*": ["@parcel/transformer-raw"],
    "*": ["@parcel/transformer-not-splittable"]
  },
  "reporters": [
    "@atlassian/parcel-reporter-analytics",
    "@parcel/reporter-manifest",
    "@parcel/reporter-dev-server",
    "@parcel/reporter-bundle-analyzer"
  ],
  "resolvers": ["@parcel/resolver-atlassian-ssr"]
}
